# Generated by Django 2.0.7 on 2018-07-26 02:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('path_re', models.CharField(default='', help_text='If left blank, will use the one from group, if no group, will allow all. If given, will overwrite group settings ', max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('path_re', models.CharField(default='.*', help_text='An RE that the api-keys in this group can access', max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='apikey',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='drf_api_key.KeyGroup'),
        ),
    ]
