# Generated by Django 2.0.7 on 2018-08-10 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api_key', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('path_re', models.CharField(default='', help_text='If left blank, will use the one from group, if no group, will allow all. If given, will overwrite group settings ', max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ip', models.GenericIPAddressField()),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='drf_api_key.KeyGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
